### PR TITLE
Repo sync

### PR DESCRIPTION
**Pull request by hello-smile6**
Should resolve the PR conflicts.

### CODE REVIEW

**Comment by webdev03** [comment]
I think it's already been solved.

**Comment by hello-smile6** [comment]
@webdev03 We got it in! I snuck the rickroll removal changes into as many branches as I could.

**Comment by webdev03** [comment]
Honestly you should have plainly deleted the code to prevent clutter but it's ok

**Comment by hello-smile6** [comment]
> Honestly you should have plainly deleted the code to prevent clutter but it's ok

By leaving all the intermediate PRs, people will remember to review changes (and not just read the comment), but not just close PRs because they don't feel like reviewing.

**Comment by webdev03** [comment]
OK

**Pull request closed without merging**
